### PR TITLE
Wrekt

### PR DESCRIPTION
**Pull request by Rtanchuan**

### CODE REVIEW

**Review by ajctan — CHANGES_REQUESTED** [review]
no.

**Comment by Rtanchuan** [comment]
update it does not crash desu :+1:

**Review by ajctan — CHANGES_REQUESTED** [review]
WHAT PART OF FUNCTION DECLARATION ONLY DO U NOT UNDERSTAND. SINO COMPRO PROF MO?

**Review by ajctan — CHANGES_REQUESTED** [review]
e pano kung walang w. walang babalik sayo? tapos magrereklamo ka kasi nasaktan ka?

**Review by ajctan — APPROVED** [review]
yan matuto ka kasi maghanap ng iba

**Pull request merged**
