### PR TITLE
Add YChecker

### PR DESCRIPTION
**Pull request by CyrusVatandoost**
Added a YChecker to check if the letter `y` has been used and if `y` is in the answer.

### CODE REVIEW

**Comment by xandraureta** [comment]
Only change 2 file <letter>Checker.cpp and <letter>Checker.h

**Comment by xandraureta** [comment]
Indentation is good

**Review by xandraureta — APPROVED** [review]

**Comment by CyrusVatandoost** [comment]
I am the best

**Comment by xandraureta** [comment]
Try to be humble :)

**Pull request merged**
