### PR TITLE
Added U Checker

### PR DESCRIPTION
**Pull request by christalon**
Added a U Checker function

### CODE REVIEW

**Comment by CyrusVatandoost** [comment]
Good code. Thanks!

**Comment by KMamuyac** [comment]
What a god

**Comment by CyrusVatandoost** [comment]
Thank you LORD!!!

**Comment by ghost** [comment]
ito po ang boss ko.

**Review by saliotHannah — CHANGES_REQUESTED** [review]
baguhin mo naaaa

**Comment by christalon** [comment]
Pa approve dito Hannah

**Review by saliotHannah — APPROVED** [review]

**Pull request merged**
