### PR TITLE
V checker tan

### PR DESCRIPTION
**Pull request by ajctan**
I submitted stuffs (╯°□°）╯︵ ┻━┻

### CODE REVIEW

**Review by christalon — COMMENTED** [review]
I like the spaces between the lines, but you also need to search for lines that needed spaces.

**Review by christalon — CHANGES_REQUESTED** [review]
I like the spaces between the lines, but you also need to search for lines that needed spaces.

**Comment by ajctan** [comment]
made moar changes desu

**Review by christalon — APPROVED** [review]

**Comment by christalon** [comment]
Nc one

**Pull request merged**
